package levilin.currencyconverter.model.local

data class CountryNameLocal(
    val aUD: String,
    val bGN: String,
    val bRL: String,
    val cAD: String,
    val cHF: String,
    val cNY: String,
    val cZK: String,
    val dKK: String,
    val eUR: String,
    val gBP: String,
    val hKD: String,
    val hRK: String,
    val hUF: String,
    val iDR: String,
    val iNR: String,
    val iSK: String,
    val jPY: String,
    val kRW: String,
    val mXN: String,
    val mYR: String,
    val nOK: String,
    val nZD: String,
    val pHP: String,
    val pLN: String,
    val rON: String,
    val rUB: String,
    val sEK: String,
    val sGD: String,
    val tHB: String,
    val tRY: String,
    val tWD: String,
    val uSD: String,
    val zAR: String
)